apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.web.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: {{ .Values.web.updateStrategy.type }}
    {{- if eq .Values.web.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.web.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.web.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "app.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.web.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/env-cm: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
        checksum/env-secret: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ include "app.web.name" . }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "app.web-env.name" . }}
            - secretRef:
                name: {{ include "app.web-env.name" . }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.web.terminationGracePeriodSeconds }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
