{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "app.web.name" . -}}
{{- $fullTLSName := include "app.web-tls.name" . -}}
{{- $svcPort := .Values.web.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.web.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.web.ingress.className }}
  tls:
    {{- range .Values.web.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | default $fullTLSName }}
    {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
