jitsi:
  jvb:
    useHostPort: true
    useNodeIP: true
  web:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: jitsi.daglesia.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jitsi-tls
          hosts:
            - jitsi.daglesia.com
