name: renovate

on:
  schedule:
    - cron: "0 2 * * *"   # daily at 02:00
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: docker
    container:
      image: renovate/renovate:41
    steps:
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://git.daglesia.com/api/v1
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: '["Daglesia/domain-infra"]'
          RENOVATE_GIT_AUTHOR: "Renovate Bot <magdalena@daglesia.com>"
          LOG_LEVEL: info