apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.constants.clusterName }}-superuser
  namespace: {{ .Values.constants.namespace }}
  labels:
    app.kubernetes.io/part-of: shared-postgresql
type: Opaque
stringData:
  username: postgres
  password: {{ .Values.postgresql_superuser.password | quote }}