apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: n8n-app
  template:
    metadata:
      labels:
        app: n8n-app
    spec:
      containers:
      - image: docker.n8n.io/n8nio/n8n
        name: n8n-container
        ports:
        - containerPort: 5678
        env:
        - name: N8N_SECURE_COOKIE
          value: "false"