apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-fixed
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: authentik-outpost-proxy
    app.kubernetes.io/managed-by: goauthentik.io
    goauthentik.io/outpost-type: proxy
    goauthentik.io/outpost-name: authentik-embedded-outpost
  ports:
    - name: http
      port: 9000
      targetPort: 9000
