web:
  secretEnv:
    AUTH_SECRET: ENC[AES256_GCM,data:ltx2FfcLmlTabT4SnXd6zWIXg1Udw5f8zpR0e4R5bZJuGZq7FyIncg==,iv:MvWDdRyL1TR7whAO55lIIzffGS1cRm1xS/1uOOpeAvo=,tag:p3L1l+sYzkeVgWpdjasQqg==,type:str]
    AUTH_AUTHENTIK_ID: ENC[AES256_GCM,data:pfy+GbCtdIXQT2m/4FTezjuvInqtwWlX9KB/BfbtpaB1Ejj1glcJKA==,iv:6eEN+Tlv9ERPbYPM1vVyb53aKTwpyXVqwdql194NwOE=,tag:gyVVkI2FxSDCEeCYITwe8A==,type:str]
    AUTH_AUTHENTIK_SECRET: ENC[AES256_GCM,data:ETTMTsQdqYqU63BYMM9fPYG2WpipTHn3/sxTXolKmHSP8LY9nc4fPA==,iv:nJN2TQ0tSo+t7oHpagD6JSBjczyKzcJPQJq8PI1JMUw=,tag:8dljR4FkKxc/Y4kXCXWRIg==,type:str]
    AUTH_AUTHENTIK_ISSUER: ENC[AES256_GCM,data:Ry4kU6jZy8Fpqh8RskNLAer2BZEXjmifeMM4MB016VSI6WspP9xUte1vvrEYDdG/x6jGIpc5UOJ5,iv:iVgGHoaNfPdRZIpx+ZZhuDmCe7kKlaO9Iz1rHa1/FXo=,tag:211UJyNKjGE5W7JkixCvdw==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV1NsaCtzRmVwcE85bGFs
        c0JtUE9LSHlNVU5SQlhreVJwbzNwUGVTc1gwCndQZ0lPWGkzaGlDcDhvQ05kd01X
        anp2ejhjN1hYMEswVndiMEhiT2ZpNkUKLS0tIEU1bloxMzZNZFhkbW9GUldYNzg4
        TThWcDFONGpxaEJZcmN6SGozOFAyVlEKWxuVxm16JwCKZ5tSWBZeZeDPtQbfWObQ
        ko+KRzQt6msHYaWJo9wp/cc28UnqP2LZl4FyanSfJhB3ojFsf+h5Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-04T10:45:44Z"
  mac: ENC[AES256_GCM,data:OuYjs3JRW8SRyQyjVlqL5Qf8ED3i663OZy/R/AuDYcLRDTfb3ZguTPPbGJ/GL/s7Ct+MsC9NUpNyWk7+khlKy81O20RgI2Yfu6pD7k7Ddr3H7EMLzT3E3/scVj3IbnsWN3y1oFE20he8IOop00XDAoM5grfIrn0EtbCS0r9AhSI=,iv:zgBct/mGOzX2163vX5ADk6jOZxPgQRmAErpao7Oo314=,tag:PjUuXocvwmiWodOV62Z1Dw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
