web:
  secretEnv:
    AUTH_SECRET: ENC[AES256_GCM,data:Mhr+Fc5wF+TobXK7O4aFT6ixB53fhmAn6axFGk/fkwUnZLkWuBGqlA==,iv:jh/KhsZkNDWf8Em29+KkwEJfz/gGYPRtEf5Q3GL6iZg=,tag:19rOF1Ytxu7Lf10BW36T5g==,type:str]
    AUTH_AUTHENTIK_ID: ENC[AES256_GCM,data:0vcKMhScDIjJGO7rUgWFbzlUu5I+VPrjzoQ2WmzjWY1Fld70XrtvEg==,iv:gj5kxRu2BUMrwrZiC66T9lXNXt3h4vOBOwtbGr26F4U=,tag:0qifquVKlVrwvf+wgK5V9w==,type:str]
    AUTH_AUTHENTIK_SECRET: ENC[AES256_GCM,data:xwwG4a/Jcx2N0TuYmHRg/uABENvGKMH+Y0fgfp4FJFOm46e/ulQVBckw1IF5328uZArNdoWN6IAe7zG+8/pulovVhm7GdhcagrkoteYoNF1hxgN+oxqBjjQPoXsKvLn7IxOj8fdOn9JPrq0JjJy0utBgMCu+LYOrlp7VmD5nxsI=,iv:pw1W/YMjXFqA6UPLddcIMN1hR6svYo1HHkkXUvxuWQU=,tag:1qrbqi0D8geuw/SIXEd+hw==,type:str]
    AUTH_AUTHENTIK_ISSUER: ENC[AES256_GCM,data:QlwhaiQSNy7VVbJ3OstbPN383jkn4c6wwcUtF3PnRsHby2txlSGZ30adov7XLKn5eX2yMq+ZlhIE,iv:KsXy2WhG69qXUwd2NiCsDhEq23mO94ztxujrIlYpGxA=,tag:aghAOlyZSAcO5KxrHgME3A==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ME9OUGp4VHhLVHhPU0NI
        NmtPK3creFFkKzBkVUNyTXZOeXlZR2hZLzNBCnpTR2ZjckZTQ3hlL041NGJ0Y3Bl
        R3dicjN2Ymd6Y1A0YXhmV3lFUUZpbGcKLS0tIEtuVVU3YlJHYkdtdnV1QXg1dVY5
        Yyt3bTQ3aFVKWEhkQUlWdXA4eWVXNzgKElpOGyKcYXfkz+Tbty/oBdZTSQ+GuxJ+
        njfh8BIzOuLEqDwrl5xtztEU0CDuZaxu811lbdfaFs5BwjBvGkggyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-05T10:37:31Z"
  mac: ENC[AES256_GCM,data:FOegD5Yof55O78hiplkdbF30EHxcl3YQiwnIwmq6RAMPMBiVKYiueWw2Jtw6uI4rSdFeb+SshOfpvrh3JMJ6d511xRx54az/WsAJHYbJlTGnc2aBOJdCcd90gJ1tG0o6AiUnoO2pImGOsWpyQPr25CFaeSUe5X+Sg0O+uopN7Lk=,iv:Iy5pEVcofRX7d8uIrOr3AThrLiymJohP3adsARcKz2c=,tag:TiaMPdhLfs6JOWA6B5T/Wg==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
