apiVersion: v2
name: penpot
type: application
version: 0.1.0
dependencies:
  - name: penpot
    repository: https://helm.penpot.app/
    version: 1.7.0
  - name: valkey
    repository: https://valkey.io/valkey-helm/
    version: "0.11.0"