penpot:
  config:
    apiSecretKey: ENC[AES256_GCM,data:Z2PYblWqv8VQ6WkOd2ySApC/zNLs7MO0WB2VwTM59LMXLgxBmEZdYDtMMw==,iv:XzDSPPz3M36Sy8CF2tgsVusieZ/UJlFqVw4KTCYp31c=,tag:s8I+AZDQ6lcjtckqeJPf1Q==,type:str]
    postgresql:
      password: ENC[AES256_GCM,data:yMksW1riA3fo7tCXlQ0uQO8Y155ZvIz+OBJ6Bb+YREV314sdPkg=,iv:sIdB8GIuTD36HcWqJegVJ7H5equa4ViH46LvGUlhF5k=,tag:6np64fYT+msdItSZaG9YHw==,type:str]
    providers:
      oidc:
        clientSecret: ENC[AES256_GCM,data:BYcwDNaFky4DVI1vV8bDYkGsFnB2Oa0GNl6BzFoGOVsfr+ubqReJtMfztO24CmTTSeuRHv+BZtBeorBcE7ygnYxXRyKchPvs54pz55nxjhlM587z9wmYE6LOWD5Naja3fh1RAM5xXGO8Au1Akle3T0lV+SeLe9YX79vjmJyuxMw=,iv:4+WPvZAsze6Gtt2fnKbGAHu+7Grk6Fr8HldnxhP9rNg=,tag:LhNY0UqZ/OqM0x9R5uxUeg==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc2I1K2RRSGE2Y3RFSTVn
        dmt2MTVhUk5pSDc3MlZVNk0ySHBoR1RuMlNzClJ2ekFCY0hjcnBvYXdWMzVsWkZr
        YXJkK2gySFA5MDd6Mm1CZVRhdG9WaWsKLS0tIElLeFZwMUEvcnpXU3o3NEIzbGNv
        ZFVaNXFYalB5N25zVFpJOFNRNUxQYUEKmJ3QAFSETpk2ZP/cw7XFjizwdYF/Fj5G
        aXGYYEIZYF3KweYY1zCcBdDnsCNdSn3p59EyJEG3gj0p0DAvPAi4jQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T15:27:01Z"
  mac: ENC[AES256_GCM,data:fQsT3hhjZsh/qAI/KwzRT+Y3Arst7sz+KyNiXTWpr8zgzPVUFhjiQE2spElHieD0TlwF3UtKx0pQX7DSMNg3uhNBcElq1+bKUZqYRJEX6F77rEGvypQ6D1p3s7FIu609IqM+BNVJO7jaS6/8/122tc1ILmCNmkDyBqLh3yPoDiE=,iv:ZKOLYW2+q1nwaGms6LBu+iKLnaKvyL3wO6yNdlrpOss=,tag:qV/wZxKnqAXJLveMaNbCXA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
