penpot:
  config:
    apiSecretKey: ENC[AES256_GCM,data:i5fCsjlzTU/pWj88XME0gwq2eamcjxpwm/8Qyzpl7JukN3cMRpEtVcBwTg==,iv:wWgo78UU71sN3EJeqAOK8HlyluPhr157A18sJWq6l5E=,tag:VoX+9r08l6HpBugVW4Rq9w==,type:str]
    postgresql:
      password: ENC[AES256_GCM,data:McjtI/X5gZpGDfKt+k6/MeUvEhIAJGWuyXCG2tANzcG9YK8gqyY=,iv:3tCqb0gcWQDdsFl4oLKEZoEzNxrj8yoQb4hp8d/GNh0=,tag:ge7hFOucNrXA6CPbozyNIQ==,type:str]
    oidc:
      clientSecret: ENC[AES256_GCM,data:5hdcT4PjMzthOo+DTBwSYv3c4oV36JEco2lAo0lcAF0UBwzMbn5KieTmM6/BKvNdtbJWVLgbcIpnUMQllOCHBO0ZPhhoerYCHpvj+EOINCSmRfo1czvTC5INTQCmQ7a/q962LK8lom4PIAqGoHdGY5bhoS9JxnBxINlbXmtdD2w=,iv:V47V5HbOOUVaJjNCZ5q7jDBxf8wkGeLkUMf8G01pmHY=,tag:5XZqZCk7vN4fLHT9GjnuZQ==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRHVhcU9BUGx4MUpvSi9R
        VnQrYm5WK21RNUVwYU1XUjVFZWg4bWpWQWtBCkVpSGpCczBET0laMThWTVRHa2xJ
        eUYwMitYMnpLcUJlWHVCb0lyZVNXZlEKLS0tIEVoUWs1dWc1dUU3aW5NbUllOWNQ
        ZGdJSWxaSFBGNnRyT1JKRmppMzVaZEkKheh9X3U65HndPRS0OmChxt/cdODlxldZ
        WKIpDHR/Z6IN6lkrq5RFfCFWYwqMn2RHCfo2mSWoEFpPQUU91vwnSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T14:41:37Z"
  mac: ENC[AES256_GCM,data:hWKxgZjoE6E5NlEBCdT5eweh/t9JzoUvcOABQsAG+guyzH88CZ4ziasFCHW9JD/PxjSaZ8omIs/Z165UbYkflajQ43maPL1dN5Re7ycQ3ZxKvBzKpI27VkPfDhqbDRXPin1KK7CHWYD2G3UUxpYZCBwMiY3rsadolzNdGufB/t4=,iv:iI5CNCW8P7jdDnk5Hoh0EzV1/73i4sJ/UJ1NbcmONLk=,tag:uUpfOLU8kMv+/kt9rI8LRw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
