penpot:
  config:
    apiSecretKey: ENC[AES256_GCM,data:ebu0JmPyYmrEJkyOkSqFHq/BomMloEzfXOz+YW0LjwSzwGIoGN4VvkkL2wApKtDd+iW/rTVT9ZxCp//gaqrZ2AGgy+NmnDQXcPH+WnlOSdwoNoShDDg=,iv:HWLmAp/d/eJcplzVlW27DCjFxrVDn75V1hY1z6hx2F0=,tag:zE+/Tlc3yKAdZJoQnTBafQ==,type:str]
    postgresql:
      username: ENC[AES256_GCM,data:H6X+mtFFuC5LBj1w0v5M0qc2AjMhEzOYiC+KlhcGhyx6,iv:moTDRxyTwxTdrY7iMCJq5L7Mb29fNMhOcNYqYKpnDYM=,tag:0DqDL7/it/LUZgLkKGz/Ww==,type:str]
      password: ENC[AES256_GCM,data:G/raELT76NfY1w/a5IFtyt0KINRodz4YGNiYPa+a5Q==,iv:Rx5QXX9CRZofbH/SFzTEzwtvicgaA0ntJsZh2S0hg7g=,tag:C+yp9KBBHDezsAjJ7o2kQg==,type:str]
postgresql:
  auth:
    username: ENC[AES256_GCM,data:r0YFGwd7s4EKO+XKSuW4m8V1PNte9jWgjyBo/hGrukyi,iv:dtQqkRIkG8Y7mzw+hPCKKCSXgMY/K5EqMRCbHDt/RG4=,tag:0yDJOpL5kdX11FSATDUgUw==,type:str]
    password: ENC[AES256_GCM,data:rjvOkFM1qY8ut8ztEnSYPBHf5D6wo4eqZkzM0jhlKQ==,iv:0MevG+4c7QNOnaX1Xs5TjLxYV3UhCpJeWhyJzJ/9ep0=,tag:92W7n1k8JLFRJqXFUYzzRw==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTTFSMGtvYzBoWGNDMjBD
        Vk5tdzlRRzU4RnFPREtIc1RqQ2hRQUZPcFR3Clc1Tmd1UStCUjZVSlZGMmJnaVd3
        b1hYRytWVHAzTmxQRkJjbEtxd2J5MDAKLS0tIDZwTUFTN2VBMXlBL01OcForMEVG
        WStwRDhic1ZQVXdqSDVXOVo1T3p4NjgKnkCpb0HB76rpo7yqllGxcuX+RMTShkA7
        laTSo6cjVfpTSxLANngW8Zle4u2c7JQzN5xYXBcutknXk+1/6WbvYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-12T11:37:11Z"
  mac: ENC[AES256_GCM,data:nW5wH0H5j+UyK7+j95FaOHkUCAuW2U5vKhs15DNNuvM3WajryPZV83mxBo5/Ak3qYn14wYiIoY9E72PzK50TuJKEpAh09jpPTJsam+2EgQisyb8Vc5xfEQw/HLtIjiUUXJTU6SrcRMTKUAg1ItGhs6M+fvh/K/mAGrJ06T7Phg8=,iv:N7CO+r7955y9B8ZxjYdpLMXGcfSYIwfmWB2+Ow6pgAk=,tag:rElrmI/hkO3DzOVU6pyTTQ==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
