constants:
  storage: "20Gi"
  pvc: "penpot-assets-pvc"
  pv: "penpot-assets-pv"
  storageClass: "penpot-assets-sc"
  node_affinity_config:
    node_limit:
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - dag-mini-pc

penpot:
  global:
    postgresqlEnabled: false
    valkeyEnabled: false

  persistence:
    assets:
      enabled: true
      size: "20Gi"
      existingClaim: "penpot-assets-pvc"

  config:
    publicUri: "https://design.daglesia.com"
    flags: "enable-login enable-prepl-server enable-login-with-oidc disable-registration disable-login-with-password"
    telemetryEnabled: false
    postgresql:
      host: "shared-postgresql-rw.data.svc.cluster.local"
      port: 5432
      database: "penpot"
      username: "penpot"
    redis:
      host: "penpot-valkey"
      port: 6379
    providers:
      oidc:
        enabled: true
        clientID: "2Xx3SzAbpEqOcIvbBtTKsIDu1SxhqQkNqn0uLo3f"
        baseURI: "https://auth.daglesia/application/o/penpot/"
        scopes: "openid profile email"

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - design.daglesia.com
    tls:
      - secretName: penpot-tls
        hosts:
          - design.daglesia.com

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dag-mini-pc

valkey:
  architecture: standalone
  auth:
    enabled: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dag-mini-pc