postgresql:
  password: ENC[AES256_GCM,data:1MXHZte+VmZaTtqgtZQMPTm3VUuadG3nwXvGFz2poMpZv4eeI6g=,iv:f6h9TllUVS0p3UFq+z9ClV6za1Kqsj5Rfu65l4zN/6Y=,tag:POfUM5vbUtbF5t4lqH6qkg==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaE1POFFBdlBpS2ZBWlBR
        dnZQektBREl3TUVCcENVekdEY3RSbGRVRkQ0CldvQmNlNjBCUzgvWVRqZlROajFm
        TVcrTlBHMVlWb0pibHY1TnJKSnErRjgKLS0tIHBtU21NUllMMUlxeEhsSGRodEdW
        bE1ZMm4vY0t1Vkt1SWVwTWFBMzBvQmMKe6xrrp4p+bVo3JT+4zgY+0LsaJC8t1fZ
        EbToxQrHJvv/dM7DUpE5Q/sG2s2amcucE04UshTJVYnfhVgUJa4UJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-29T11:31:58Z"
  mac: ENC[AES256_GCM,data:X7ziCQWf6mAJu62uqmN8AmCtR2Pyhwvy+e164XE6Zf3Fq5VGV5NKn/kjc38y+SjywIzHAbXqdjM1qSA7yVU+g+iZiX68Bu05OEyVXpAjRwjXUxnV97rxIEZJ4xExNpa5n3I5MoTLLC9qRrNMzE2Q4fhJGoTLwHFhIzdpIhJFbio=,iv:4ESoigKPkbPV5cA2pE4poeyHTi0j1VM3+07AykWQ4LM=,tag:OSteFPhtrEfNL7ImVJJ5Aw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
