postgresqlUser: ENC[AES256_GCM,data:xZnQBqwGpfuWFtY=,iv:72RhFYsf/BkaTLJgNoxU6wWfk1w7HHLCwqXmFZYcl6U=,tag:G6B8zJTOWkG1u9yNTYkI0Q==,type:str]
postgresqlPassword: ENC[AES256_GCM,data:9OaJxJSAXaceM5Rmdsz17kjO93x6mSWk8iMPc/hCbu8vBQ==,iv:nxteyZuAU+9Hp4qCEcm5jKRIiKoPu5YuyBeSzn9x6hU=,tag:dIWEvLNPHdpEchbGDoffjw==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWEtwQnFocGRiMGhVL0I1
        aHhkRVRETWNCeVlJRWg0RWdmSmlpTFZmYW1RCk12MUwzOE5qaFJMRFZTMi9PZWhL
        ZGpVZytvQmhDdCt2Yk5QSWMreXNxNDAKLS0tIFo5RGZKcTVFbDI2ZnhQcjRSdjVN
        aGxvaXo4bWt3SjBnUGVuV0FUY3hMVHMKOjlZDtjTJnSaQskEJSM/FmSuP39inHb7
        jc1MMX67+91c6QWTGTvr4yU2PMUdpY4RKJa9aCX3+b8cOtpEWlGDfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T12:07:35Z"
  mac: ENC[AES256_GCM,data:VsN8NfomaKjYRtiIuo708fis9wWWXr3j/n/eYYv3Zv2XQVOW8kW5togA8DZerzDlpZ+hXm/YdfRjx9O6QIm6A+KCD5f/YaSros6MkdvSNbaVwftcNa7HrylBxSO0BOQSzV/aemz9lymONREyJTrrFexZvYLr4I82P3zWMN1E3aw=,iv:DSUYP08iqIP4nOIzLcDg0iCQUbe2yJq0T1MxjuiDTtM=,tag:j1QOiJoNPlsMRJ9GyYCn3g==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0