constants:
  storage: "10Gi"
  pvc: "wiki-docs-pvc"
  pv: "wiki-docs-pv"
  node_affinity_config:
    node_limit: 
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - dag-mini-pc

wiki:
  postgresql:
    enabled: true
    image:
      registry: public.ecr.aws
      repository: bitnami/postgresql
      tag: "15"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - dag-mini-pc
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: docs.daglesia.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: wikijs-tls
        hosts:
          - docs.daglesia.com
  persistence:
    enabled: true
    size: "10Gi"
    existingClaim: "wiki-docs-pvc"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - dag-mini-pc