apiVersion: v1
kind: Service
metadata:
  name: forgejo-service
spec:
  type: ClusterIP
  ports:
  - name: port222
    port: 22
    targetPort: 22
  - name: port3000
    port: 3000
    targetPort: 3000
  selector:
    app: forgejo-app