apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: forgejo-app
  template:
    metadata:
      labels:
        app: forgejo-app
    spec:
      containers:
      - image: codeberg.org/forgejo/forgejo:8.0.2
        name: forgejo-container
        ports:
        - containerPort: 22
        - containerPort: 3000