grist:
  secretEnv:
    GRIST_SESSION_SECRET: ENC[AES256_GCM,data:edLWDirik7Av,iv:Svqox1N4vvRVkFppGzclvL1xV7/XANMfk1PvbLCiBEI=,tag:QXsIzgXxNs25Ic69e2XUDg==,type:str]
    GRIST_BOOT_KEY: ENC[AES256_GCM,data:R8zE5UGoyjM7,iv:wa1TaM2x5pG4you/kGsLeky2GdwsvRsqmT5IRfhtA1s=,tag:dILgTjhehN9COo+ZYobELw==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpendpUks1a3BsbE94QmU5
        RG1PTHVYMGYwRitCQ2I1UWM0bkNwd2h1S1RZCk42WGhScFAwVjJxT0RCMHh2N29C
        RE80SFpLTDhhTXAydUhNVnIzK3FBc1UKLS0tIGxEa0FMZmY2V1hxbDFZMGdPY3Bs
        MTRIWU9SanJHMW9GTDFrWXhFL3JrUTQK5fp5f4xwRq4bMXGuM5V3vFid6urQoPZZ
        hGxIJWHjos6tM+b9GeA4J14Df0zs83c0/lgJ9K+m27UUsnnTUOfhLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-08T13:25:05Z"
  mac: ENC[AES256_GCM,data:dfmmuO/NlgVVIPMCB80A4KkOdpoyOvZ5TI1SoqIjqeccqK7s0XBnjvdgV175NdetREQfPPJKwf2SSQD3S45CrBs3PVuNOwe7b5hOqh2HKVexNuE5uwy2bXjh42H5w36rs8agCyad35iOXW9WOMC00bAA5hdSCcD6esOg/Pjmh9o=,iv:p/z24fl9jz64hN3rKTUncaBMsaBfu2rU0jnuGRU1Ax4=,tag:hLo9vb76x1jVDywZ4+OCqA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
