victoria-metrics-k8s-stack:
  grafana:
    adminUser: ENC[AES256_GCM,data:ffcJp+slEq5IxHz9V5WvOI0XdsSZ1g0L,iv:71w5X7TEQpOiwJ+Pqoa8lMHWVNyWQYx+scCQW+PtH1s=,tag:rBwiyidkVUpwxESQVk/gtA==,type:str]
    adminPassword: ENC[AES256_GCM,data:sVZ+E1+KDT16SBGZCFlEVMyrcPjDkEoy3DALJcc6Zk3EowR1z4WD925Xj7tSJg9GeFe9/6hSyvOhVC7BYgEOIhEWR3XTwuU=,iv:D51m+NKc2XYHP4duCZt7+ASCupYKLXvGTETxiKc0bxk=,tag:Cri/uCmlYcQK9R/LnkJX+Q==,type:str]
  alertmanager:
    spec:
      configRawYaml: ENC[AES256_GCM,data:SbxKFN0NV45BoeJ2ykLMWtZH66Ep3d1gDjob+qVvE8UNDfNShAelxIhg/8b+90jVrIA4oUeg18TAlMGJLz5NSK4=,iv:ux3Aqa00OVEb+J/rqPJvPOzCthHBzOblEype56m5V80=,tag:ZB+zepzl6h4aW1srbMq62A==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOXhGdERrNU9hci9PTDZM
        RjU0aTlWa3ZVQmxZYk1TT2xBa3hhK1o5RUhZCjMyaHZxam1DVTBOSVNlMUVNdVNX
        dSs2cVlUSGdQdTVqOHMrN1d3L1h3L28KLS0tIFhSeE9FTUVEbTQ3b240Vk9UYS95
        R2ZRbElmNzRJK1ZYbzVMdGFLRGxSL28Kp8fvdHH8PFv8LcrX16sjLA6lqKnExzrk
        5Df9C0P729RbdiPiLb90ZUdizhxQzJXdy9TxgiJyTbhWWTsLMm6/oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-08T13:37:05Z"
  mac: ENC[AES256_GCM,data:mg+Zo0xSpE4taUX8JtW0sszqVfrm3qS6//+6ebY0fg6MKV6ON8s9rUlz+W/Kz/2Zlv7apfigHSD0tCGgz/p40iT///9ER5+pX6rDimEC1VIqwe/wSHdjFzgI5UlNQJPDUxs1ns8Yq1xj/IuWBl+YkL345B6A2nja56pCR/E3YnQ=,iv:/ykhAiylT8QhWJqSPfwz4rgZWN2nmtrRXiYcpmyMb18=,tag:ArJgKQ4Fczzv/wfnSL1R2g==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
