victoria-metrics-k8s-stack:
  grafana:
    adminUser: ENC[AES256_GCM,data:Dc8AsCf2ZxfEjj0sdLpFszk2V5eUbsVo,iv:yKQnlKD5juxpFCY1cNPRyqfU+TD2NJxqimn3Q0IFsYw=,tag:ehbIXW03sNDZkZSxwVM5/g==,type:str]
    adminPassword: ENC[AES256_GCM,data:teSc/cZ9g+lEGjf6AkE9ymw1AotOaYp4q6Nu1LgNaV1gJoonUWCoVW8kwIK7kpr3HHd/VogECQzYWP/tP2n93lkD9tptVyg=,iv:8X30FIXOA35/k8xaFQfXKVXIp6p6sEf7vlEpfiXrUjY=,tag:7tmRPurftY2oFYH5TizhTg==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQUgwWDdLUVRsSGUycHY3
        QlBRblJhT1VGQStNOURkTkJtQk9mNUtFRXhBCituQzVYMlpMcXM0NXFwS2p5SGFp
        WVMrTGRzMEw5ZzRFcFlIR2tiUjBrSUkKLS0tIGlXWTdvU3ZOcnFmV2FLNjZpYXlu
        T01XcEtSNE5SNWRYM3ExUTdWK0FiekEKqSUHyyRsBFPAn6hC+kDcXdGJUdSkdpAG
        dL/dGsRxkCHRkUcY/Ls5ACsKgnomdHF0B4tvcsyiZlqPNyR9YlDNsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-08T14:24:49Z"
  mac: ENC[AES256_GCM,data:anA8vwb/CK12ouFavDngAPMyfwY5xKngYofPe84WbFGHROLAgJM+9U4VeJf0vdwwwfFxjQ7KRUgfBTVmcVeeDnc7ycPa5TtwrAL+Z/M81LJ96mJ3rkhvMQT3cb46mxUt5V9q8RlshpnNkzDyjgayUx5k2pWXQB0kz7O+5UAnRu0=,iv:uhK3jSnoNC6tuys7WpdqbDA28NdyefCfQVbdGPkQlWA=,tag:vNOo3fvsk1LlenhdBdNvpw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
