databases:
  - name: ENC[AES256_GCM,data:zBB15vTohg==,iv:Ybtb5N4YVHHJ55O2gFkOk1a0iyBuRyTHf86aTCrGCYk=,tag:YTdw3YT3Kfjo0jkgC85Qew==,type:str]
    password: ENC[AES256_GCM,data:YKjSsby0peBn7iCzlTjizS4FIQdztEV2CQMJVt9WqA==,iv:nou7WRJpFKyykZ5UKucJYScw9OuaHcuk0G7hvNxcGvM=,tag:kpz+9ivsCfvuiz1fa5svpQ==,type:str]
  - name: ENC[AES256_GCM,data:uaSNpGg6,iv:elDlKbYF0UQWPjHbpLvB1nb3KIXoCeCrmUlES+4SSqM=,tag:QJVBjojP/+Kzz1Pd73kmNg==,type:str]
    password: ENC[AES256_GCM,data:ow3j7qlZkgkqF1gO84Fgx+E2wxH7mSxN7l4iDgIU8xg=,iv:LjwnmWDPiZiefODQN+ccwP28aycIYEC17g0I08lO72w=,tag:h+KgQfRN0cmwYq8Qt1Jkuw==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUW9RangxUllJSWpWZ2o3
        eC9FQW9YVFp1MlVXbDNQYkhqSHkvck9wR1dVClQvVXFNRlpyTEZJV1BEVmxkRzlY
        V0NSZk9SVmZCeFFnQTZzTElEaWc3QTAKLS0tIGZFZHZjZVBNcjFLRkR2OHVLS0xx
        Yit1dFNSdUIwOVlLbVhibEVEQllISEUKkeMNTbdW4ods9K0SCKK6wz/8m1e1S0e0
        zWigVOVGqaagw/XIAvPytqiI/lnmXmfDgV/VgeTO4h91MuC4s61bUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-24T10:46:06Z"
  mac: ENC[AES256_GCM,data:pBtZbD4T2PYDedclIJwzUJRGcVdk28AeW4yACKTctI6vToum98Rgn7L1/gIvl4isIHifs1dxOvMKrmMOBLN24zPFiBD/0+s2lIv1QqyfAPxGLT+E3Z7coXDmqkSX7ljLRkRVynhY0eRyG1NziFXTEJBH6Rw8ORwikuChTr3nMj8=,iv:Z79Wkm/z+AmTL2zWsTFrAfaj3cF1EC9rIDUuGgBdS8I=,tag:SyBWmdb5pz5YwbmjD96Hug==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
