postgresql_superuser:
  password: ENC[AES256_GCM,data:HcZ1wGj1PKDfEiAemrGf3Q1L/l8zmCDUUNYNWlBPtNmOCKcFQ1p3nQ==,iv:YXkrFsSgegzVFsZAs+ZfOd2iX1zj8ppkzzyXMBz+Bjc=,tag:v32EERDoQkdh8jo9gqQXzg==,type:str]
databases_secret:
  forgejo:
    password: ENC[AES256_GCM,data:KcH4NyM+CGzOLAzi5yA0biT3j7jWw6BtuGlz2nvlfDxspr1TofM=,iv:bGuIxq14TJeVURPT/KqMJSpz8X6C8JAjx7+D2ycxCKU=,tag:MOdkGdz/6KVB3CyH0UTgHw==,type:str]
  penpot:
    password: ENC[AES256_GCM,data:mBjEhCCrU95kATgNLDuLvjaOKzWnpsmVUTwS6NIDjH6X8TSQmY8=,iv:l4B+ElfUritxl/1RZDgN+3V05g95tzVU5f7fHm2lgWo=,tag:OZPW3M4sytm/DV63XJ4UKQ==,type:str]
  wikijs:
    password: ENC[AES256_GCM,data:27L+oPXax8kMy1A9tc3P6qdn7nodnCzgI7GMpNCpNQBI4T9FOew=,iv:f/dU+7yKRkkMJijvFaVpaD3pVF5JX70+rra3+BujQ5s=,tag:S7qI8kJLI5Oq2L2WA5thJQ==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0U5K2VmYWwzYjlIcE1z
        MG80S3dkdHI0NXVsUi95RllBSUhWcVVubkFNCklNZXd3SHRSM0JHeWxPVlhLZ0Uv
        MjFpMlh3L2dLdkZVbkhJa2pOdnQ4NWMKLS0tIEFqK3E3VTlGNU1odU5KL28xcEsw
        NEVhMTBnVDhqZXVtYTFtUUcxblNxWlkKdREipy5wPNvUw1ZDJHe1fDdQkSrtu2o+
        kgGXH6AIptdaDUyscaLELjzyNQYsnzSzDO8yCegRG6esahhvdyxRjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-29T11:30:25Z"
  mac: ENC[AES256_GCM,data:sU2Ya3G/A02MF923yaAd4wYUyyhMnvE93DBH7PkYNnKlzjPcnAoRGeHBauoikU+r5w3hD9xVOdHKJqVk052S7njz5Pgg4Bo3GgMAy/oUEOB74E5zthICQekavTW+65dO+s/hGpl2jk8x0yopaKn+xvu133SSkkxvXkxk+KErCts=,iv:EgIj9kWnveiVFa3Xp96iy0FyFwslQmgfsqtq3IHwgUI=,tag:r5Ks8O986m2pgyaN+0jxqw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
