postgresql_superuser:
  password: ENC[AES256_GCM,data:TiHCVxK/JO/49bV+l3JGScfgzPX/3Zm30C3V91a/bizMad70gKHB8A==,iv:Gahvv2wn2gp81/Q/fYvzSpwWF6r6ZtORd2JPQM5gk6A=,tag:ApFB9vkkkj6Sn9KhWRfetw==,type:str]
databases_secret:
  forgejo:
    password: ENC[AES256_GCM,data:RhhabSwcO5lJCWWQJsWa3VylYjK7MelJYIXThJXx+yNwtXweVxc=,iv:i8mXDRFMm4KQpKf7vjmNVKkTGfiIwH7H07d+EjItFrg=,tag:z3jLnzMT9Q/PXOcbR5RxDA==,type:str]
  penpot:
    password: ENC[AES256_GCM,data:5jOgPqZPqedS2J3mc+wqUDLBglzZsRhwv+0XIeMlwjU0nkWSCRs=,iv:gu/+r8UrMqjYx51vxOb9jCfo62Bx6lSOx9Hqsu+Dhw0=,tag:xE+EF0h6QOhRh0NsJ7WC9Q==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVak1Zc0k2NVBNZkZyTUxW
        bkNoMGV4d3hNSDZBWWRTQkQ1WXUzZlkxRlFRCk9vTG81OG9TU09KaXZ5RmxZTkJS
        Qm1aemhSUE14T2RTeHRJMDd2MWV6cjQKLS0tIGJ4U1RDSENlT0pwRjFyRFpIdWdi
        alBib0lVbUNpYmtXTnQ2TVMxc05HVlEKzyFB3wSIqm7F8dl2lApJ6nqsRxXJxmX3
        t83hqfOssWGbAusI2Y7Mu837qjJjfDwl20ZjOAAlgwJfw5Mb7tG2/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-24T11:08:40Z"
  mac: ENC[AES256_GCM,data:/feRAnvSFH7T0VYCmuBJCBxIjmGphaAYnZLyGV6kkKjKmtaHci+PG/afFtycX6ts+toOqdY52ImVNgiW1Z36rHJHDDRL0TDB2+5QvUP6heqjpCOD6pFPEDJnRDi00CI0IiguyS70j1N7VDkQk3vUHtX7Zqh4+989+iStkC1++to=,iv:sqQ3ZdH2zuQQTNQHdj7pbPg95YsNBq/dVoUF/v6KLYY=,tag:vmvbu47asvrZYmmpffEVoA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
