apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grist.name" . }}-env
  labels:
    {{- include "grist.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.grist.secretEnv }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}