apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
  namespace: forgejo-runner
  labels:
    {{- include "forgejo-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.runner.token | quote }}