apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forgejo-runner.name" . }}
  namespace: forgejo-runner
  labels:
    {{- include "forgejo-runner.labels" . | nindent 4 }}
automountServiceAccountToken: false