authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:2z/Uk0gprJHQzVGGssGXDeBkwIgMGngsUGCx4X8pxTBEZwSG1qdNwEVdmySJwg==,iv:zYX86Fm9fzOsbDUbE5/s81rScJyXlJ1JMrvlV5rcp2k=,tag:3VGkukgKsuJLntjglb1k9w==,type:str]
        postgresql:
            password: ENC[AES256_GCM,data:SaDP0YVrWleEEe7sZfNVY/vMEbuXYWd9hwNNe7cWMZMB51//ckgD4/QO,iv:T5V4wkrNAyR3LJYiU8wya4hZ8b5CGndHvziQYsFctWU=,tag:EccZQrsqzSliNXZMhooSdQ==,type:str]
    postgresql:
        auth:
            database: ENC[AES256_GCM,data:KI/Ln0AyrKlYqlDpKC7v/smz7KD1,iv:IUsKzRJZDzJMRGg6Lw9oA8rec1R6xQVTLLjs/xSyc8A=,tag:ZeLU9K59y9qeuKdODRxmlQ==,type:str]
            username: ENC[AES256_GCM,data:uNMQ3gaQq6yH3jgQgllUtx6wvw==,iv:+syPEgi+4gLJ3RxGc+1ptOnxvwUzxpTr1X5QJgXWlr4=,tag:k8sZIG9b+DJMZ0WIJ50Fag==,type:str]
            password: ENC[AES256_GCM,data:WjiKzTWG0TY/oOUXQ8gQdAdDBEwncpP4xA4=,iv:Rm9H0u+Fk52NBbxi0y4s9yc5LwspAm900CUFf/QqZkU=,tag:4fTyCWvZrdqmJoa1qMvD/w==,type:str]
sops:
    age:
        - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVnNjOVZKK05ITHlnekJw
            TWxvNFNZT01aRnEzaGcrU2VPUlJ1NlpseTNZClJoRGZZWkdiTis2QkFVdEpzcys3
            alJKSmR0QmxVV2hmZXc1bHcvTjJ4NDQKLS0tIHdCRlpMbUNzM0JXQmxFazROKzBk
            em9iN0hGSFJ4cGY2V1FNYWJrUDFzU2sKIbiq/B9RQKgcbFGXLctSZ9WFXcBBJ5fO
            w7FhC9+XtRtAxnGJCGXgZPKoKYHDqkUhlrv9AuS8zCeid7A5xKKKXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T15:25:50Z"
    mac: ENC[AES256_GCM,data:4vaD9w2UR725GF1VNxTVwVdJDfc550c/ywJuMM0eGJmXQLA5kYflubOfLeFlq9HQfQso6HTABzQ2A3Y+rPHlm2lfsyVLtPpJzxI8PfjsBmfWOlFLK6ee8AOodEfnksJfAYYFMdcC+96cmsarYgce9vo0QRXVo3x2VFOwXAVIshg=,iv:91aqa0bIXmFK7+t2PmsuK5nSPzxZneq6pjSLFkj/zi8=,tag:8xK/+UJrGWey82+OS4yzJQ==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0