authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:Imx7mGQR2PGoG1TuoiiXoN3XpoCJuqbG//9HJl+/ghJ2stzQcFoasIx39ZBP,iv:Ddco4RdLKxNY76W3lWzAWx3YHX4YB3ZI8A+D5xzuf94=,tag:xzLQ9oAsI+KRGzRr76aAdg==,type:str]
        postgresql:
            name: ENC[AES256_GCM,data:6g4j0QhGdG9tbh3Nlmf8ChR84Xswq31+,iv:2OvW96RQbb9fTAr3VHWJsql3hflzVoDfP8vXo4OiVGw=,tag:xeLcnqabswM+y32a5mwBQQ==,type:str]
            user: ENC[AES256_GCM,data:WBtqhXBNHw2iUG9hG6ByD4F+bVIjMnnP2T/hl3CCXHygUlH5Vi9UkUXmJw==,iv:G28lNiEJVJjdawZvBiUb5fLRxwZ7XvkQkxBv+vQYnQc=,tag:8IbQzaW+NooG3bMhz9GhbQ==,type:str]
            password: ENC[AES256_GCM,data:1a5KZhFXdeiM4QVMBSvfuLqEhrQaZMZuq8Tq3SisxPQQyWdB,iv:52q6EnuAfM6uVz7pFpiZp9BDRQMgiwUhYT64p4X23bM=,tag:GEQgk2peTTCX8L+vdzYlfg==,type:str]
    postgresql:
        auth:
            database: ENC[AES256_GCM,data:TawV9E+JKZSXflWAwYBVO4eKtiQdXizw,iv:GvzJLxsHSMdZwInVyDRPCDQzxZzRRXKD51Xlh4+3Etg=,tag:HrHhJ1PdNx5Brn/fqFokmg==,type:str]
            username: ENC[AES256_GCM,data:gKFWXvCqRxqmKtrQwFFOhrugH0HBRqwkqaTu9Y51HHFjcoPzpDBUTPotOQ==,iv:2GEPEbyciCbY6BePedfW1c3N0Hug5mwHDMR0/bOuglw=,tag:SiP9fShnJufuxRFxHZuH7Q==,type:str]
            password: ENC[AES256_GCM,data:V++8l7/4SN7JDPqZz/ZoH7fBx8JoqMTY5jOenUcA2DdQsIAJ,iv:UMfCXRFO0gaFCbkLMlCXPhLPy+lYByAxLec3UHFAdcY=,tag:DnA4qqvXYakHFF93NAYhig==,type:str]
sops:
    age:
        - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZytObjdZRlVCVmFqSkxw
            M1lMaE5WM3B0NDZxeUV3Y04rckZkMlFvbEVVCnZWT3Z3ekZQTW9MbmlJcW9kY2Rl
            S3Azc0JnM3NPUEJ4OUl3bGZxV1dhRUkKLS0tIENjZVpXM2U3ekowTm5QZ040SXNz
            SENwcDNMc1pTUFNYczAyZE5CZmpJREkKLC9qElPT2RNKOx8K3bkLbwQTkBt9XBp2
            KttN+GNJyJSPCb5nSUHWPDiCqRjMee90ZXEmEHC6ISzLc+nIkuuL0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T09:39:36Z"
    mac: ENC[AES256_GCM,data:JhsDxVZhjRumJC9sQGh4iSjnzv6NoNoSnOnb9LOsGbq38yLFimdkODWxnGgDt+ipXMEoewNMzAzlz7vIjsBYR0ZlvwYvWVK3mJ2zr4jtYDTa2+bdQiSp3FxlMBoOTFUsXEsHxWPgJhTQ0Decvxo541NBI44FfixQ/uNgDF4qdlM=,iv:AmJ8umVEhkm3ZABAQahXo2KuXGK9s8/ABwW5CEMHriU=,tag:3zw7EYCN1698omRN3Gvnxg==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0
