constants:
  host: auth.daglesia.com

authentik:
  authentik:
    error_reporting:
      enabled: false
  server:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - auth.daglesia.com
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: authentik-tls-cert
          hosts:
            - auth.daglesia.com
  worker:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - dag-mini-pc
  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        size: 8Gi

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - dag-mini-pc