runner:
  token: ENC[AES256_GCM,data:4pOeLNgj3U7JJhZ8Z4W3Uh+ToMOOASVcd4pFXfEBLygA6zarwq0Q1w==,iv:CceHrm7zrbwM5EaLm4LtdmxVg+7Hdg7G1AIUDXT64ms=,tag:DAh8E8086XD3LWrvgwvgag==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU2x2c1NKMlA1UEp5MTgv
        YkZxZUpIOXhwN0ZYVzhTUWxyU2Qza2RSVkJRCjNnWkNUN0pENUJIK1FKellXVVBl
        Wi9TV0NqeWNzYVErZVYrT3pzTS81Y3cKLS0tIHU1M1FjcWZ4UGp1cllING1sU3Mv
        OU1LZ21sVmtUK25kUG9KK01CR1dhTVUKTh7X0q2DGHP5+8SrF90k+pvmUpVyhdEy
        szVGbHuytmHlF85iIkspBWlAvtSBVYw2ETd4As5d2rPPdlD4L0Dc0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T21:34:16Z"
  mac: ENC[AES256_GCM,data:1zIsG7U7yEUb5trxXPpRFtY/+OfyIPeJOjZ7ny9X9NVYdZCqItjEaceoCqSSTcw0hzU365HjAMW7E5VwGTvody0y+osOGamxwL8yC4NFmtPZ6Bp5PYsvzmna8TJS1NYUfEFG30MIByeRQXvvNr3eTImS8MdbSRvZtuiI8G739js=,iv:y4JTCvhPPZD4c+s9ANOlp2lqNRzvZ4Fsr2c+7B81OO4=,tag:RJIKXYsj7dUOn971SSFxbA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
