n8n:
  main:
    secret:
      database:
        postgresdb:
          password: ENC[AES256_GCM,data:tyPek0vLUrukXuZay1Dx+j/iMpefgfr8tNAFF3KLabnVnNJzv8U=,iv:5ItvcGFWwWQc6i6ACLoDaOW8jeyejXIXGr7eQLozJrY=,tag:HjA559fGUE48WrT8j2R4UQ==,type:str]
      n8n:
        encryption_key: ENC[AES256_GCM,data:1onPlnvJ3BabuFyOTkFdolloYnM3wTZHPjnPSC0=,iv:cML1ajcCbmce7DCiqD3p6vEo/rHqTkgq7oXc/qcdvsQ=,tag:aKQ/lmAsmG/9bheQvTAEAQ==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK0U2UFRvb3ZjMFF1UUd4
        dG42bk9mc01zWkU1Z0U5NW1LZVFLZHMvbkdjCnkzdG9lZVJzMDFFUFE3Ni83QTY5
        anBxWFJjazJ1YVNmTS9wNGZHRXhvSFEKLS0tIG1KUWZyYWtZMDlhUWIwMTRBUExK
        Qkpqa0cvb0tYc2dFQTdQdzFnUnFiVDAKS4XTkUQ5//F/f27Yeo5S43Mc+jkmCpds
        k5f+iVZX0FU2bq/cuF2zSOR14piI33dIkerAt9eP1IwGNptU2AhyfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-16T12:47:13Z"
  mac: ENC[AES256_GCM,data:sb+1TO+pf54h+TACLLcC4XDZ/3MdFU8raaeVy2wyYTeot89eOLLkRG3z3b/1LFmdDYSre7Xs2tYbgtfv/dkT4JvxaCqWCy1+Umfonooij4LVXDo1wt8vq/cEnU/PAIizHa0iF6zvAxOdEHhPCW4o0ZEaz7goAM+87AB/BI3CMsA=,iv:cRp2H98lNjcemoSYkt85t/X0E/TReQM0JWAqOiN+3VA=,tag:uU+4cgUONU5F42AGb5XPoQ==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
