n8n:
  main:
    secret:
      db:
        postgresdb:
          password: ENC[AES256_GCM,data:ouFGYYGr25HNQbsvCYciSx4ZUMUuDnYiM0t+rb0pJR5kYbXpZVA=,iv:c0a0V74JyRw9NBjhIPWjKTE6KRNvTpGoXCMV7qNp/o4=,tag:uCJO/SDbBaYluqaFdAPPYg==,type:str]
      n8n:
        encryption_key: ENC[AES256_GCM,data:v+8Z0e7AtBmZ0Q7MgUfMK5y9isZtbLGOmhJNIoI=,iv:/cbbP+/Ao0jX72xKliA5gbE3rBhnTADkPGWG7i4nIoc=,tag:G3HnLgZuw19qu3CgDYMkIA==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYjEwRFVxdkJNbEVKc0xH
        enRTVXdJVENxZjRCWG9nSmFhWm5zaTZNcFNRClN1Q2ZNRVV3SXF1enN4eis3UnQ4
        ZTlqNkJFdWJVWC9NR3RRWWhLVEZ5N0UKLS0tIGRCZ01BeHF6a1A1MVNPaWt5NkdR
        VlZTSTY5emFreWgySEx3ZWFqVGtXTm8KiEYHA8HiWS/OElO9LHhxk3zdbLVg8qxS
        0IFTpL9ipSoy3ifQxAqDPSpXFF7oF2qu7AxD22MEZ/NcVK3dg/bGAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-20T13:00:51Z"
  mac: ENC[AES256_GCM,data:tq3Z96+/RhDfRfuEzijlOYUkQySMkVTUg3N0UHe0Bm7bygPSo0fehN8J/4ZIt+eoz4HDV5zjtDjY46Q0P0JXfVR0264wtlxAmUqEjfVTzMBn85vZbdQoM83Q+jmlsT/f/xnHSt4rB1ZS5JQ7rIGWjooHHL9kADQtg1TziYSzEpg=,iv:M6am7QVgbunQSd/Q9eOfbnu9pY1KlERr2wZOf4wBNbk=,tag:kez0DWQf7GW6DtN/vElA2w==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
