apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/Daglesia/domain-infra
    path: charts/cnpg/operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Daglesia/domain-infra
    path: charts/cnpg/postgresql
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true