{{- if .Values.clusterIssuer -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "clusterIssuer.issuer.name" . }}
spec:
  acme:
    server: {{ include "clusterIssuer.issuer.server" . }}
    email: {{ include "clusterIssuer.issuer.email" . }}
    privateKeySecretRef:
      name: {{ include "clusterIssuer.issuer.key" . }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}