joplin:
  env:
    APP_BASE_URL: https://docs.daglesia.com
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: docs.daglesia.com
          paths:
            - path: /
              pathType: Prefix
      tls:
      - secretName: joplin-tls
        hosts:
          - docs.daglesia.com