web:
  secretEnv:
    STEAM_API_KEY: ENC[AES256_GCM,data:TZ7M12YeNFPPnyX/lB9PS6KN4xgbeYCi0jEsbZB9AYs=,iv:DNlXKOXtzXDFxxY/3jtBJHQtwyPtBenlh9ZDBK4gL2Q=,tag:VE/STGhdDFnrJ1vyeiNqdg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:GCZPOv5enBX1ndY4ow/0E/SvZBI8BIhbdTbwtr2aFWD3Q+h08jXBY4xj/4qU3s0P1Ecj3Vh8Z8W5zklEH3ZEVj7JGPAxlXtH7n9Y1I6FhflSMJUcRBl7EcaDEm41M56Wf0H3t4yn8Kcu73uWabnO3osABS9NI1jly/LI5NHJDCwzznwnq/VNCde2s5pGzaHBZyo=,iv:omeZtuW2fUblg7ix7gjCpZrNRt+QqlQ1XRbiOJWPv24=,tag:8FFimAeBCZYksYkNd4uzLQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:NcsUKMJnQBKMMI0Xoipwz7ZX9VSAEt1LdI8ISlARy9IZSiqODeHmvA==,iv:+2+nFk7OFE9HHQ5Ec+NRrpb45CBIDT0CwsGigPH4Qfs=,tag:P/1a34CJp4+AK045EAM1bQ==,type:str]
    AUTH_AUTHENTIK_ID: ENC[AES256_GCM,data:Y1wgAEwAohb9p+WSw2NLTtJPmA8wclV4OjjaqwF03fV7P02W44wNyQ==,iv:MAIeSIHnDt44HnuCk9YHOnaD0A1DonBvFWqEQ/QvIq4=,tag:fyIB0HaggxhaIbrNEiVrSQ==,type:str]
    AUTH_AUTHENTIK_SECRET: ENC[AES256_GCM,data:TSuSsAFxLh4jnF8FhuOJN5q6PQJdpk207Zqrhwk1SEBjGUDDu7pxjDoBQByC7GkJGsB0Z+ld3DEMcc+F6BmN9MAl9KE6L0PWb0u27OV8SlvvVEaBS4JfyRkEMGzzV/Dp7hfVtpICkWmdFhfs7wEuFoW3KCpxEW2Pqloj43gwFOc=,iv:RCOlz0la1SNaZVL5t1kGDW+V6Uvm4X5k37Pb7ROYlvY=,tag:K7NxTEeKadztgze9a4LU+A==,type:str]
    AUTH_AUTHENTIK_ISSUER: ENC[AES256_GCM,data:cobhljuAETUR1ccI35kOt6AFOVzTW1d0Wcx42PxpF4VU4vhirhlBFR4Dg8f8oSw+7fOl8CvIC+DaGzu00A==,iv:VDC3hnP0eD4gVTTgd9x5WkinG5lfJwasp+erSxOyGoo=,tag:rBoYtxatCtkQuzYX8UM7lQ==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUWlVREliR3hlYzhhY2VU
        cGdFZTg4eHUySzlsNVNRNHloTWdQRm92NmlJCkw2U3lGQjQ4bjBTOENEVUw3NEd0
        T0tiSk5iSkl6TmpaOVgxL3R4eWg5VncKLS0tIHpRSmZpS0k1azBTZ0pweXNPcWFB
        alZ1TUcvWFF6NEF0Sm81cFJrTnpqeFEKtcgzvPcN5YfqueACaE6NfGYPJs2iGx+l
        iUzvriIC/p5hgIHEVAcZkpv3Z1ze5VkM+EP6eQdmjMIu9sbcabWz9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-27T08:13:03Z"
  mac: ENC[AES256_GCM,data:hOH1wthi9OhztLntjpoMJGMgYlR2ZUDXaCCud2c1TGUJavuAs5L/jrF6AESyb873SpvgUEvQ136RAke64W5lxPzCvKnNj6ubXu5XT7ewaD6O9C9LDBtcoVOmeWKQtaGyvdCpNoC5NXdje6kEh/UvFake4nkM5Wx8lxyaPt4N0uY=,iv:8sDfxb/Gj0d2iCJjw9H9zdclS4kkqNxtnr5Hf3+/AcY=,tag:N68XXCmY61JCMJzkeiiGcQ==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
