web:
  secretEnv:
    STEAM_API_KEY: ENC[AES256_GCM,data:sPX0tc3OuiLExEmlVR/UwhBACbJYeW0Gy0uG8hYw+KU=,iv:oiwk3Y1biVW1CT6vTAQ5E5sGKJfhCa/EpeJxVeMi02U=,tag:S+0Z/yTUdJh7/66PjqGYyQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5b64pZnbK2MkHOVPCFy1vdj1jI2ZAC/G/3Sb3zJhtQWsTQOtExGxQp3DYfOUm8dY0JeOJ8sVZiuIv4SPFdcj2MIjpWXwFvIIKRjlBXqgTtZIC+ep8rjqNHPxTnxOoYHL2GVfwQ0hHNtnBTc59XSt1dJdfuT5QnSRSFvkbs1epXOoXI9VaHoh8gLT3FOFZdICUd0=,iv:zAPMZP/APrbXRl6xFKiRi8RD9dG+wiydfbuqFwbXrj0=,tag:4oHnt1C/dwC9lXm0VYrb7g==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM21nR2QyY2pYMVZZWVpW
        WGJ3YkFmcHZaaW9HUXpUa2RsSnROaWZaN2hFCkxha3lEUllaRFE2N2JOV05ZNXAx
        NUo4bWJPQThxWUovem91eTlSTHp4Ym8KLS0tIFBLMmV6YlVZalhMMHdjUlVhN25O
        MXg0RXYwKzlPSVUxOENnQ2lESFBobDQK+g6L7j6BRXw3ngRs1fiXYZVEUyjTmrM6
        l32UtkVNXxIIaCsOOpjYPySy8O9xWViBnCSythQBp19eEH4rvwHkUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-26T09:44:19Z"
  mac: ENC[AES256_GCM,data:U3Q9gpWI2b//arNWR9PrNmikdFntXNFCXnO1qo5zv9+KZR3vvRUlTU2oiMdHjJuX37hDU7HIXd3P8Do+jCNO53j80PrumbnhwrRdwfBuNEE2ESwryTflKd/s486zMnwSgrtZb8OXcfF4dTd08nH06iKarjCbziHNdFghc5LZBhw=,iv:toqGEe450XMalV78gTF4XXSqUgyGt6MmcUs3FPjWBIk=,tag:CJ1CBnmLqOk+zjdnZIrOmw==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
