web:
  secretEnv:
    STEAM_API_KEY: ENC[AES256_GCM,data:0xSSTRDzDJLH6hltZmOhgZkAPwxQ5dNwHL0xyXQz73s=,iv:eb76WLv+Pxf9ZZvtPNV6759Q5uk0Awdq4nLQRqPRaNA=,tag:T3Ks5NdxmVkJQoa1uwZhAg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VPu2+Q+azHRWKR6KpkkXGBf7W6OTRw+8wfGKlpC9FDIcGRNP4suBWT5Wr7TgVsK26GfSiI9GI/65hS9I5Z/6ELcxtOSyIRmK1XoF3KPupRJrn0q5nIOaV7HbIz69dPQI4rj9xGQHbpU6IAc/1y35NJzergP2aXXLgCwMpzO8sidSkmzF/Utmmsu9r8CMJ68HSlI=,iv:eZ6LkokG0e+SEJniZ1fDzNiUSV4fdXXY3J+rNn2PI6U=,tag:f2EZ8gMK082fTIBif5Labg==,type:str]
sops:
  age:
    - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVHovMjFBTkVpRlpIdUxY
        dGN0NFBVcXhxRVMvNG5zdFdHRDV0NUM2R2dZClBoOU9uQVo4Tndva01UeGZwK1c1
        Y1ZkaVUwMmtYbFppZUdOTTBWSklHOUkKLS0tIGtMdUNRWkFkUjJyS3pyMTRWbndO
        c081ejA5M3Zhd2tsUW5FOTMrd0x5Y2MKwctdd+EeriD219WZy/rasZJxDEWqssgn
        oAmJmPwxf35Iau3aaBUG5LxYSc+5BBYBILdQSYQ102z3ecYo/ivpAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T09:46:03Z"
  mac: ENC[AES256_GCM,data:ESfBgFNOPlLrWu1hKWfQEKt/ZwXNV15vGpbq+y4idhIn4uwh+z35j/bbeOLQ4h4VLiwHdFtASynKOS7lDlya/Lzwh7xAVOIh5h8Qsg1Cf7zt9CRWwJgkPJVpb/q2hmsef8aJd9dRGSLy3r4KhvP9oAxDxG13Ux67eV47BWV09UQ=,iv:K3ds0jXjyvete2ig1Igirvysky5c7GDB608bUjmWreU=,tag:JC7/yZ4kHLV+aOiy9IZSRA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0
